### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by benceruleanlu** [benceruleanlu/Team-Website#3]
Images currently do not load properly when querying https://team4308.ca/Team-Website/.

This is a well documented issue on the internet.

**Comment by claireoe** [comment]
@benceruleanlu Please assign me this issue.

**Comment by benceruleanlu** [comment]
Hello @claireoe, sorry for not mentioning this on the README, but the team would prefer to keep this project internal.

We're working on figuring out how to private the repository while having it hosted on GitHub Pages.

We've updated the README to reflect the situation.

**Comment by benceruleanlu** [comment]
Fixed after moving off of [https://team4308.ca/Team-Website/](https://team4308.ca/Team-Website/)
