### ISSUE TITLE
Add icons to socials in footer

### ISSUE THREAD

**Issue by benceruleanlu** [benceruleanlu/Team-Website#8]
His Royal Highness, Maximilian the Great, has expressed a desire for the inclusion of illustrious icons adjacent to our esteemed social media links within the majestic footer section of our digital domain.

**Comment by maxikyuu** [comment]
thanks pookie

**Comment by benceruleanlu** [comment]
We only have one social (Instagram), keeping it in line with the current styling for every other footer item seems ideal.
